SELECT U.ID_USUARIO "ID USUARIO",
              U.NM_USUARIO "NOME USUARIO",
              SM.ID_SMARTMASK "ID SMARTMASK",
              SM.NM_SMARTMASK "NOME SMARTMASK",
              SM.DS_SMARTMASK "DESCRICAO SMARTMASK"
FROM TB_SMARTMASK SM INNER JOIN TB_USUARIO U 
ON U.ID_USUARIO = SM.ID_USUARIO
WHERE ID_SMARTMASK BETWEEN 6 AND 12
ORDER BY ID_SMARTMASK;

SELECT 
              ID_SENSOR,
              NM_SENSOR
FROM TB_SENSOR 
GROUP BY NM_SENSOR, ID_SENSOR ;


